name: Containerize Static Site

on:
  push:
    paths:
      - .github/workflows/containerize-static-site.yml

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Static Site (Vite or plain)
        run: |
          if [ -f package.json ]; then
            npm install
            npm run build
          else
            mkdir -p dist
            cp -r *.html *.css *.js dist/ 2>/dev/null || true
          fi

      - name: Generate Dockerfile
        run: |
          cat << 'EOF' > Dockerfile
          FROM nginx:alpine
          COPY dist/ /usr/share/nginx/html
          EXPOSE 80
          EOF

      - name: Build Docker image
        run: |
          docker build -t static-site:${{ github.sha }} .

      - name: Save image to tarball
        run: |
          docker save static-site:${{ github.sha }} -o image.tar

      - name: Create Git tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release & Upload Image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          files: image.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
