name: Generate Dockerfile

on:
  push:
    paths:
      - .github/workflows/gen-dockerfile.yml

# Grant write access so github-actions[bot] can push tags
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "CMD ["echo", "Hello from Dockerfile"]" >> Dockerfile

      - name: Create Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git with GitHub Actions bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Dynamically generate or set the tag
          TAG_NAME="v1.0.0"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"

          # Push the tag back to the repository
          git push origin "$TAG_NAME"

      - name: Create GitHub Release & Upload Dockerfile
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
