name: Build & Release Docker Image

on:
  push:
    branches:
      - main            # or your default branch

permissions:
  contents: write     # allow tagging & release uploads

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo 'CMD ["echo","Hello from Docker"]' >> Dockerfile

      - name: Build Docker image
        run: |
          docker build -t app:${{ github.sha }} .

      - name: Save image to tarball
        run: |
          IMAGE_TAG="app-${{ github.sha }}"
          docker tag app:${{ github.sha }} $IMAGE_TAG
          docker save $IMAGE_TAG -o image.tar

      - name: Create Git tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release & Upload Image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          files: image.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
